/* Generated By:JavaCC: Do not edit this line. LabelPatternParserConstants.java */
package bibtex.rdf.labeling;

public interface LabelPatternParserConstants {

  int EOF = 0;
  int LPAREN = 1;
  int RPAREN = 2;
  int LT = 3;
  int GT = 4;
  int PLUS = 5;
  int COLON = 6;
  int DIGIT = 7;
  int ALPHA = 8;
  int SPECIAL = 9;
  int SPECIAL2 = 10;
  int LETTER = 11;
  int NAME = 12;
  int STRING = 13;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\":\"",
    "<DIGIT>",
    "<ALPHA>",
    "<SPECIAL>",
    "<SPECIAL2>",
    "<LETTER>",
    "<NAME>",
    "<STRING>",
  };

}
