#Namespaces
ns_bibtex=http://www.marcont.org/bibtexrdf#
ns_unknown=http://www.marcont.org/bibtexrdf#

#Properties
address=bibtex:address
title=bibtex:title
booktitle=bibtex:booktitle
journal=bibtex:journal
series=bibtex:series
crossref=bibtex:crossref
url=bibtex:url
key=bibtex:key
    
publisher=bibtex:publisher

author=bibtex:author
editor=bibtex:editor

#Output lists

entryProperties=all
verbatimProperties=note, annote, key, author, editor

#Flags
createDate=false
createAddressResource=false
createSeqForPersonList=false
createPersonResource=false
createCollectionResource=false
createEntryList=false
createDatatypes=true