##########################################################
# Namespaces

# declare namespaces in the form
# ns_<shorthand>=<uri>
ns_rdfs=http://www.w3.org/2000/01/rdf-schema#

# if a namespace with shorthand 'unknown' is declared, 
# this namespace is used to create RDF property names
# for unknown BibTeX fields
ns_unknown=http://www.swrc.org/default#

# if a namespace with shorthand 'bibtex' is declared, 
# this namespace is used to create RDF property names
# for known BibTeX types and fields, if they
# arent mapped to DC or RDF properties
ns_bibtex=http://www.swrc.org/default#


##########################################################
# Types

# types start with an upper case letter
Mastersthesis=bibtex:Masterthesis
Masterthesis=bibtex:Masterthesis
Mscthesis=bibtex:Masterthesis
Periodical=bibtex:Publication

School=bibtex:University
Institution=bibtex:Institute

Author=bibtex:Person
Editor=bibtex:Person

BibFile=bibtex:SourceFile

##########################################################
# Fields

# fields start with a lower case letter

address=bibtex:address
title=rdfs:label
    
booktitle=bibtex:booktitle
journal=bibtex:journal
series=bibtex:series
crossref=bibtex:crossref
url=bibtex:url
key=bibtex:key
    
publisher=bibtex:publisher

author=bibtex:author
editor=bibtex:editor
    
personFullname=bibtex:name

sourceFile=bibtex:sourceFile
fileAbsolutePath=bibtex:absolutePath
rdfLabel=rdfs:label

##########################################################
# Field output lists

# for BibTeX entries, output all fields 
# plus source file info and label
entryProperties=all, sourceFile, rdfLabel

# for person info, output the full name
# plus source file info and label
personProperties=personFullname, sourceFile, rdfLabel


##########################################################
# Flags

# do not merge year and month as one property
# (in the form YYYY-MM)
createDate=false

# do not try to create an address resource
# and split the address into components
createAddressResource=false
    
# create a Seq for author and editor lists
createSeqForPersonList=true

# create a separate resource for each author/editor    
createPersonResource=true

# do not create separate resources for collections
# (proceedings, journals, etc.)
createCollectionResource=false

# do not add a Seq of all generated entries to the output    
createEntryList=false