#Namespaces
ns_bibtex=http://visus.mit.edu/bibtex/0.1/bibtex.owl#
ns_unknown=http://visus.mit.edu/bibtex/0.1/bibtex.owl#

#Properties
address=bibtex:hasAddress
title=bibtex:hasTitle
booktitle=bibtex:hasBooktitle
journal=bibtex:hasJournal
series=bibtex:hasSeries
crossref=bibtex:hasCrossref
url=bibtex:hasUrl
key=bibtex:hasKey
    
publisher=bibtex:hasPublisher

pages=bibtex:hasPages
note=bibtex:hasNote
volume=bibtex:hasVolume
number=bibtex:hasNumber
chapter=bibtex:hasChapter
annote=bibtex:hasAnnote
edition=bibtex:hasEdition
howpublished=bibtex:howPublished

    
institution=bibtex:hasInstitution
organization=bibtex:hasOrganization
school=bibtex:hasSchool

author=bibtex:hasAuthor
editor=bibtex:hasEditor
abstract=bibtex:hasAbstract

#Property types
numberType=http://www.w3.org/2001/XMLSchema#string

    
#Output lists

entryProperties=all

#Flags
createDate=false
createAddressResource=false
createSeqForPersonList=false
createPersonResource=false
createCollectionResource=false
createEntryList=false
createDatatypes=true