#Namespaces
ns_vcard=http://www.w3.org/2001/vcard-rdf/3.0#
ns_dc=http://purl.org/dc/elements/1.1/
ns_dct=http://purl.org/dc/terms/
ns_bibtex=http://www.edutella.org/bibtex#
ns_ow=http://www.ontoweb.org/ontology/1#

#Types
Article=ow:Article
Book=ow:Book
Booklet=ow:Publication
InBook=ow:InBook
InCollection=ow:InCollection
InProceedings=ow:InProceedings
Manual=ow:Manual
MastersThesis=ow:Masterthesis
Misc=ow:Misc
Periodical=ow:Publication
PhdThesis=ow:PhDThesis
Proceedings=ow:Proceedings
TechReport=ow:TechnicalReport
Unpublished=ow:Unpublished

Conference=ow:Conference

Organization=ow:Organization
School=ow:Organization
Institution=ow:Organization
Publisher=ow:Organization

Journal=ow:Journal
Collection=ow:Collection
Series=ow:Series
    
Author=ow:Person
Editor=ow:Person

BibFile=ow:SourceFile

#Properties
address=ow:address
addressLocality=vcard:Locality
addressCountry=vcard:Country
    
date=dc:date
year=ow:year
month=ow:month
    
title=ow:title
shortTitle=bibtex:shortTitle
    
booktitle=dct:isPartOf
journal=dct:isPartOf
series=dct:isPartOf
crossref=dct:isPartOf
    
pages=ow:pages
note=ow:note
volume=ow:volume
number=ow:number
chapter=ow:chapter
annote=ow:annote
edition=ow:edition
howpublished=ow:howpublished

url=ow:url
key=ow:key
    
publisher=dc:publisher
institution=ow:institution
organization=ow:organization
school=ow:school
type=ow:type



author=ow:author
editor=ow:editor
    
personFullname=ow:name
personStructuredName=vcard:N
nameFamily=vcard:Family
namePrefix=vcard:Prefix
nameSuffix=vcard:Suffix
nameGiven=vcard:Given
nameOther=vcard:Other

source=ow:source
fileAbsolutePath=ow:path

#Resources
EtAl=ow:EtAl

#Output properties
entryProperties=all, rdfLabel
personProperties=personFullname, rdfLabel

collectionProperties=address, booktitle, editor, journal, location, month, number, publisher, series, volume, year, shortTitle
proceedingsProperties=address, booktitle, location, publisher, month, volume, year
journalProperties=address, journal, month, number, publisher, volume, year
seriesProperties=publisher,series
bookProperties=booktitle, editor, series, year

#Label pattern
defaultLabelPattern=(<author>:<author>+'. ')+<title>+(<booktitle>:'. In: '+<booktitle>)+(<publisher>:', '+<publisher>)+(<month>:', '+<month>)+(<year>:', '+<year>)
articleLabelPattern=(<author>:<author>+'. ')+<title>+(<journal>:'. '+<journal>+(<volume>:' '+<volume>+(<number>:'('+<number>+')')))+(<year>:', '+<year>)


#Flags
createDate=false
createAddressResource=false
createSeqForPersonList=false
createPersonResource=true
createCollectionResource=false
createEntryList=false