log4j.rootLogger=WARN, STDERR, FILE

log4j.appender.STDERR=org.apache.log4j.ConsoleAppender
log4j.appender.STDERR.layout=org.apache.log4j.PatternLayout
log4j.appender.STDERR.target=system.err
log4j.appender.STDERR.layout.ConversionPattern=[%p] %m%n

log4j.appender.FILE=org.apache.log4j.FileAppender
log4j.appender.FILE.file=bibtex2rdf.log
log4j.appender.FILE.append=false
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.STDERR.layout.ConversionPattern=[%p] %m%n
