#Namespaces
ns_vcard=http://www.w3.org/2001/vcard-rdf/3.0#
ns_dc=http://purl.org/dc/elements/1.1/
ns_dct=http://purl.org/dc/terms/
ns_bibtex=http://www.edutella.org/bibtex#
ns_iswc=http://annotation.semanticweb.org/2004/iswc#

#Types
Article=iswc:Article
Book=iswc:Book
Booklet=iswc:Publication
InBook=iswc:Publication
InCollection=iswc:Publication
InProceedings=iswc:InProceedings
Manual=iswc:Publication
MastersThesis=iswc:Publication
Misc=iswc:Publication
Periodical=iswc:Publication
PhdThesis=iswc:Publication
Proceedings=iswc:Proceedings
TechReport=iswc:Publication
Unpublished=iswc:Publication

Conference=iswc:Conference

Organization=iswc:Organization
School=iswc:Organization
Institution=iswc:Organization
Publisher=iswc:Organization

Journal=iswc:Journal
Collection=iswc:Collection
Series=iswc:Collection
    
Author=iswc:Person
Editor=iswc:Person

BibFile=bibtex:SourceFile

#Properties
address=vcard:ADR
addressLocality=vcard:Locality
addressCountry=vcard:Country
    
date=dc:date
year=bibtex:year
month=bibtex:month
    
title=iswc:title
shortTitle=bibtex:shortTitle
    
booktitle=iswc:conference
journal=iswc:conference
series=iswc:conference
crossref=iswc:conference
    
pages=bibtex:pages
note=bibtex:note
volume=bibtex:volume
number=bibtex:number
chapter=bibtex:chapter
annote=bibtex:annote
edition=bibtex:edition
howpublished=bibtex:howpublished

url=dc:identifier
key=dc:identifier
    
publisher=dc:publisher
institution=bibtex:institution
organization=bibtex:organization
school=bibtex:school
type=bibtex:type



author=iswc:author
editor=bibtex:editor
    
personFullname=vcard:FN
personStructuredName=vcard:N
nameFamily=vcard:Family
namePrefix=vcard:Prefix
nameSuffix=vcard:Suffix
nameGiven=vcard:Given
nameOther=vcard:Other

source=bibtex:source
fileAbsolutePath=bibtex:path

#Resources
EtAl=bibtex:EtAl

#Output properties
entryProperties=all
personProperties=all

collectionProperties=address, booktitle, editor, journal, location, month, number, publisher, series, volume, year, shortTitle
proceedingsProperties=address, booktitle, location, publisher, month, volume, year
journalProperties=address, journal, month, number, publisher, volume, year
seriesProperties=publisher,series
bookProperties=booktitle, editor, series, year

verbatimProperties=note, annote, key, author, editor

#Flags
createDate=true
createAddressResource=true
createSeqForPersonList=true
createPersonResource=true
createCollectionResource=true
createEntryList=true
createDatatypes=false