#Namespaces
ns_vcard=http://www.w3.org/2001/vcard-rdf/3.0#
ns_dc=http://purl.org/dc/elements/1.1/
ns_dct=http://purl.org/dc/terms/
ns_bibtex=http://www.edutella.org/bibtex#
ns_iswc=http://annotation.semanticweb.org/2004/iswc#
ns_rdfs=http://www.w3.org/2000/01/rdf-schema#

#Types
Article=iswc:Article
Book=iswc:Book
Booklet=iswc:Booklet
InBook=iswc:InBook
InCollection=iswc:InCollection
InProceedings=iswc:InProceedings
Manual=iswc:Manual
MastersThesis=iswc:MastersThesis
Misc=iswc:Misc
Periodical=iswc:Periodical
PhdThesis=iswc:PhdThesis
Proceedings=iswc:Proceedings
TechReport=iswc:TechReport
Unpublished=iswc:Unpublished

Conference=iswc:Conference

Organization=iswc:Organization
School=iswc:Organization
Institution=iswc:Organization
Publisher=iswc:Organization

Journal=iswc:Journal
Collection=iswc:Collection
Series=iswc:Collection
    
Author=iswc:Person
Editor=iswc:Person

BibFile=bibtex:SourceFile

#Properties
address=vcard:ADR
addressLocality=vcard:Locality
addressCountry=vcard:Country
    
date=iswc:year
year=iswc:year
month=bibtex:month
    
title=iswc:title
shortTitle=bibtex:shortTitle
    
booktitle=iswc:in
journal=iswc:in
series=iswc:in
crossref=iswc:in
    
pages=bibtex:pages
note=bibtex:note
volume=bibtex:volume
number=bibtex:number
chapter=bibtex:chapter
annote=bibtex:annote
edition=bibtex:edition
howpublished=bibtex:howpublished

url=dc:identifier
key=dc:identifier
    
publisher=dc:publisher
institution=bibtex:institution
organization=bibtex:organization
school=bibtex:school
type=bibtex:type



author=iswc:author
editor=iswc:author
    
personFullname=iswc:name
personStructuredName=vcard:N
nameFamily=iswc:last_Name
namePrefix=vcard:Prefix
nameSuffix=vcard:Suffix
nameGiven=iswc:first_Name
nameOther=vcard:Other

source=bibtex:source
fileAbsolutePath=bibtex:path
label=rdfs:comment

#Resources
EtAl=bibtex:EtAl

#Output properties
entryProperties=title, author, year, label
personProperties=all, personFullname, nameFamily, nameGiven, label

collectionProperties=booktitle, editor, journal, date
proceedingsProperties=booktitle, date, location
journalProperties=journal, date
seriesProperties=publisher,series
bookProperties=booktitle, editor, series, date

verbatimProperties=note, annote, key

#Label pattern
defaultLabelPattern=(<author>:<author>+'. ')+<title>+(<booktitle>:'. In: '+<booktitle>)+(<publisher>:', '+<publisher>)+(<month>:', '+<month>)+(<year>:', '+<year>)
articleLabelPattern=(<author>:<author>+'. ')+<title>+(<journal>:'. '+<journal>+(<volume>:' '+<volume>+(<number>:'('+<number>+')')))+(<year>:', '+<year>)


#Flags
createDate=true
createAddressResource=false
createSeqForPersonList=false
createPersonResource=true
createCollectionResource=true
createEntryList=false
createDatatypes=false
createPersonNameStructure=false