#Namespaces
ns_vcard=http://www.w3.org/2001/vcard-rdf/3.0#
ns_dc=http://purl.org/dc/elements/1.1/
ns_dct=http://purl.org/dc/terms/
ns_bibtex=http://www.edutella.org/bibtex#


#Flags
createDate=true
createAddressResource=false
createSeqForPersonList=false
createPersonResource=false
createCollectionResource=true
createEntryList=false